{
 "title": "Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "domain", "query": "label_values(host)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Geolocation",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({geohash=~\".+\", url!~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\"}[$__interval])) by (geohash,city)",
     "legendFormat": "{{ geohash }}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=~\"$domain\"} !~ \".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Errors are all requests where the response status code is a 4xx or 5xx.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({status!~\"(2|3).*\",host=~\"$domain\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Worker Usage (100,000/24h max)",
   "type": "gauge",
   "description": "Cloudflare offers a free tier of 100k requests per day\nIPInfo offers a free tier of 50k requests per day\n",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({status=~\".+\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({status=~\"2.*\",host=~\"$domain\", url!~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({status=~\"4.*\",host=~\"$domain\", url!~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({status=~\"5.*\",host=~\"$domain\", url!~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Sources of Traffic",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({host=~\"$domain\", type=~\".+\"}[$__range])) by (type, network))"
    }
   ]
  },
  {
   "title": "Top Pages",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 10, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "topk(15, sum(count_over_time({domain=~\"$domain\", path!=\"/\", path!=\"/robots.txt\", path!=\"/index.xml\", status=\"200\"} !~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__range])) by (path))"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "topk(5, sum(count_over_time({domain=~\"$domain\", status=\"200\", browser=~\".+\"} !~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__range])) by (browser))",
     "legendFormat": "{{ city }}, {{ country_name }}"
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "topk(5, sum(count_over_time({domain=~\"$domain\", status=\"200\", os=~\".+\"} !~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__range])) by (os))",
     "legendFormat": "{{ city }}, {{ country_name }}"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({host=~\"$domain\", path!=\"/robots.txt\"} !~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__range])) by (country_name))"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "topk(5, sum(count_over_time({domain=~\"$domain\", status=\"200\"} !~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__range])) by (device_type))",
     "legendFormat": "{{ city }}, {{ country_name }}"
    }
   ]
  },
  {
   "title": "Top Cities",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({domain=~\"$domain\", path!=\"/\", path!=\"/robots.txt\", status=\"200\"} !~\".*(ico|js|jpg|jpeg|png|webp|css|webmanifest)\" [$__range])) by (city, country_name))",
     "legendFormat": "{{ city }}, {{ country_name }}"
    }
   ]
  }
 ]
}